[WIP] udp-server
SW805F20/pozyx-location-tracker pull request #2
Opened 2020-03-02 10:59 UTC by andpaacoke

Tror egentlig det er done, men kan ikke lige finde ud af om jeg bør teste noget af det, og i så fald hvad der skal testes

2020-03-02 11:21 UTC, Moesgaarda commented on udp-server/socket-multicast-receiver.py
> +        sock.sendto(b'ack', address)
Skal man sende acknowledgement når det er UDP?

2020-03-03 09:03 UTC, andpaacoke commented on udp-server/socket-multicast-receiver.py
> +        sock.sendto(b'ack', address)
Nej det er ikke noget man skal, men det gjorde de i den tutorial der var lavet. Vi kan bare fjerne det hvis det er

2020-03-06 09:29 UTC, Fatdet requested changes

2020-03-06 09:29 UTC, Fatdet commented on udp-server/socket-multicast-receiver.py
> +        # Create the socket using ipv4 and UDP
Du skal følge vores vejledning i forhold til dokumentation givet i testplanen

2020-03-06 09:29 UTC, Fatdet commented on udp-server/socket-multicast-receiver.py
> +        data, address = sock.recvfrom(1024)
Hvad er 1024?

2020-03-06 09:29 UTC, Fatdet commented on udp-server/socket-multicast-receiver.py
> +        mreq = struct.pack('4sL', group, socket.INADDR_ANY)
hvad er 4sL? og socket.INADDR_ANY?

2020-03-06 09:29 UTC, Fatdet commented on udp-server/socket-multicast-receiver.py
> +        socket.socket.__init__(self, socket.AF_INET, socket.SOCK_DGRAM)
Hvad er det for nogle ting du sender med?

2020-03-06 09:29 UTC, Fatdet commented on udp-server/socket-multicast-receiver.py
> +sock = SocketMulticastReceiver(multicast_group='224.3.29.71', server_address=('', 10000))
Det må gerne være nogle variabler i toppen af koden ala noget lignende konstanter i C

2020-03-06 09:29 UTC, Fatdet commented on udp-server/socket-multicast-sender.py
> +class SocketMulticastSender(socket.socket):
forkert dokumentation

2020-03-06 09:29 UTC, Fatdet commented on udp-server/socket-multicast-sender.py
> +    def send(self, message):
igen

2020-03-06 09:29 UTC, Fatdet commented on udp-server/socket-multicast-sender.py
> +        self.settimeout(0.2)
Sæt 0.2 som variabel

2020-03-06 09:29 UTC, Fatdet commented on udp-server/socket-multicast-receiver.py
> +    def receive(self):
doku

2020-03-06 11:01 UTC, Fatdet approved these changes

2020-03-06 11:02 UTC, Tekrus approved these changes

2020-03-06 11:07 UTC, merged