Proj-35 Get data from pozyx and data analysis in latex format
SW805F20/pozyx-location-tracker pull request #3
Opened 2020-03-03 09:02 UTC by Fatdet

2020-03-03 11:13 UTC, Eduardsen commented on demo/find_location.py
> +        # ms = UWBSettings()
why udkommenteret

2020-03-03 11:13 UTC, Eduardsen commented on demo/find_location.py
> +        s = "POS ID: {}, x(mm): {}, y(mm): {}, z(mm): {}, TimeStamp: {}".format("0x%0.4x" % network_id,
s er et lidt usigende navn imo

2020-03-03 11:13 UTC, Eduardsen commented on demo/find_location.py
>          if status == POZYX_SUCCESS:
lidt forvirrende at det er success når den henter error, skriv noget dokumentation

2020-03-03 11:13 UTC, Eduardsen commented on demo/find_location.py
> +    # necessary data for calibration
måske skriv lidt om hvorfor det er necessary

2020-03-03 11:14 UTC, Eduardsen commented on demo/find_location.py
> +        # ms = UWBSettings()
også de to linjer bagefter

2020-03-04 09:37 UTC, andpaacoke requested changes

2020-03-04 09:37 UTC, andpaacoke commented on dataAnalyze.py
> +    # getData("C:/Users/frede/Desktop/tests/5 tag/test1/26895data.txt")
Skal det her udkommeret kode ikke fjernes?

2020-03-04 09:37 UTC, andpaacoke commented on demo/test_find_location.py
> +
Fjern unused imports 😃 🔪

2020-03-04 09:46 UTC, andpaacoke requested changes

2020-03-04 09:46 UTC, andpaacoke commented on demo/test_find_location.py
> +    a = PozyxStarter()
Kan du ikke give den et bedre navn end 'a'?????

2020-03-04 09:52 UTC, andpaacoke requested changes

2020-03-04 09:52 UTC, andpaacoke commented on demo/find_location.py
> +    a = PozyxStarter()
kald den gerne noget mere meningsfyldt end a

2020-03-04 10:00 UTC, andpaacoke approved these changes

2020-03-04 10:01 UTC, Eduardsen approved these changes

2020-03-04 10:02 UTC, merged