Proj 61 data formats
SW805F20/pozyx-location-tracker pull request #6
Opened 2020-03-26 08:11 UTC by jenspetur94

2020-03-27 09:10 UTC, andpaacoke requested changes

2020-03-27 09:10 UTC, andpaacoke commented on udp-server/find_location.py
> +        """Initializes posyz and adds tags and to the instance of the class"""
```suggestion
        """Initializes pozyx and adds tags to the instance of the class"""
```

2020-03-27 09:10 UTC, andpaacoke commented on udp-server/find_location.py
> +        """Initializes posyz and adds tags and to the instance of the class"""
Mangler at beskrive parametrene i docstring

2020-03-27 09:10 UTC, andpaacoke commented on udp-server/find_location.py
> +        position.x = position.x / 10
Hvorfor divideres der med 10? Evt. forklar i en kommentar

2020-03-27 09:10 UTC, andpaacoke commented on udp-server/mock_find_location.py
> +        """Initializes players with hardcoded positions"""
forklar parameter i docstring

2020-03-27 09:10 UTC, andpaacoke commented on udp-server/mock_find_location.py
> +        """Get the position of a tag and increments it's position with 2"""
forklar parameter i docstring

2020-03-27 09:10 UTC, andpaacoke commented on udp-server/find_location.py
> +class PozyxStarter:
Denne klasse bliver ikke brugt længere så ved ikke om den skal slettes eller der skal knyttes en kommentar til den.

2020-03-27 09:10 UTC, andpaacoke commented on udp-server/mock_find_location.py
> +        self.player_dict[tag_id].x = self.player_dict[tag_id].x + 2
Hvorfor incrementes der med 2?

2020-03-27 09:10 UTC, andpaacoke commented on udp-server/mock_find_location.py
> +class MockMultiTagPositioning:
Kunne måske være fint med en lille kommentar der forklarer hvad denne klasse bruges til

2020-03-27 09:10 UTC, andpaacoke commented on udp-server/package_formatter.py
> +        package = team_1_score
Her kunne der med fordel være en kommentar som hjælper lidt med forståelsen af hvad der foregår

2020-03-27 09:10 UTC, andpaacoke commented on udp-server/package_formatter.py
> +        package = pos_y
Samme her er det lidt svært at forstå hvad der foregår med bitshifting - måske en kommentar

2020-03-27 09:10 UTC, andpaacoke commented on udp-server/server.py
> +    def __init__(self, should_mock=False):
forklar parameter should_mock i docstring

2020-03-27 09:10 UTC, andpaacoke commented on udp-server/server.py
> +            self.time_stamp = (self.time_stamp + 1) % 256
Hvorfor modulo med 256?

2020-03-27 09:10 UTC, andpaacoke commented on udp-server/server.py
> +        for i in range(0, 4):
i stedet for at hardcore 4 som antallet af anchors kunne man tage længde af anchor listen i setup sådan at vi har mulighed for at have flere anchors på et tidspunkt uden at skulle ændre det

2020-03-27 11:23 UTC, andpaacoke approved these changes

2020-03-29 17:26 UTC, Fatdet approved these changes

2020-03-29 17:42 UTC, merged