PROJ-96 - Give team to player
SW805F20/pozyx-location-tracker pull request #8
Opened 2020-03-31 09:03 UTC by MathiasLybech

2020-03-31 09:40 UTC, andpaacoke requested changes

2020-03-31 09:40 UTC, andpaacoke commented on udp-server/setup.py
> +                if i < self.amount_of_players // 2 + 1:
Er denne ikke altid true udover sidste iteration? Er det ikke intentionen at halvdelen bliver promptet for det ende hold og den anden halvdel det andet?

2020-03-31 09:40 UTC, andpaacoke commented on udp-server/setup.py
> +        number_of_players = len(self.player_tags)
Vi har allerede en variable på klassen amount_of_players som brugeren inputter

2020-03-31 09:40 UTC, andpaacoke commented on udp-server/setup.py
> +            for k in range (0, (number_of_players // number_of_teams)):
k bliver ikke brugt til noget? og skal number_of_players ikke divideres med number_of_teams?

2020-04-02 08:31 UTC, Eduardsen commented on udp-server/setup.py
> +        Function that assigns players into teams.
synes egentligt det er en lidt tynd kommentar, det finder man jo ud af ved at læse navnet. Måske lidt mere om hvordan, fx hvorfor er 0 et parameter der bliver appended til teams i slutningen?

2020-04-02 08:31 UTC, Eduardsen commented on udp-server/setup.py
> +            self.teams.append(Team(self.TEAM_NAMES[i], team, 0))
er det meningen 0 er en counter for mål?

2020-04-02 10:03 UTC, andpaacoke commented on udp-server/setup.py
> +                if i < self.amount_of_players // 2 + 1:
nevermind det lignede at // 2 + 1 var en kommentar så nu giver det mening

2020-04-06 07:38 UTC, andpaacoke requested changes

2020-04-06 07:38 UTC, andpaacoke commented on udp-server/setup.py
```suggestion


```

2020-04-06 07:38 UTC, andpaacoke commented on udp-server/setup.py
```suggestion


```

2020-04-06 07:38 UTC, andpaacoke commented on udp-server/setup.py
```suggestion


```

2020-04-06 07:38 UTC, andpaacoke commented on udp-server/setup.py
> +                for k in range (0, size_of_teams):
```suggestion
                for k in range(0, size_of_teams):
```

2020-04-06 07:38 UTC, andpaacoke commented on udp-server/setup.py
> +        players = copy.copy(self.player_tags)
Måske beskrive hva copy.copy er

2020-04-06 07:47 UTC, andpaacoke approved these changes

2020-04-06 07:51 UTC, Eduardsen approved these changes

2020-04-06 07:52 UTC, merged